### DISCUSSION TITLE
Ability to respond with text/html

### DISCUSSION THREAD

**Discussion by rokf** [ogen-go/ogen#1121] [Q&A] [answered]
Hello,

I was wondering if you've perhaps ever considered adding support for `text/html` responses? Just basic stuff, no schema handling or anything like that. Automatic content type header and string response from the generated method would be good enough I suppose. I've tried it and it doesn't seem to be working as of now - I get an error saying that the content type should be `application/json`.

Thanks! 🙂

**Comment by ghost** [comment, marked as answer]
You can map `text/html` type to ones that `ogen` supports by using `content_type_aliases` option.

Create a `.ogen.yaml` file with config:
```yaml
generator:
  content_type_aliases:
    text/html: "text/plain"
```

**Reply by rokf** [reply]
This works, thank you!

```yaml
"200":
    description: OK
    content:
      text/html:
        schema:
          type: string
```
