### DISCUSSION TITLE
Can i force the generator to only generate client code ?

### DISCUSSION THREAD

**Discussion by ymolists** [ogen-go/ogen#1152] [Q&A] [answered]
Hi folks

Thank you for this tool. This is the second one i am trying so far in go.

Is is possible to stop generating client code ? I don't want to use the generated server code but right now i dont see a way to avoid generating it.

Best Regards

**Comment by ernado** [comment, marked as answer]
Hi, please try following config:

```yaml
generator:
  features:
    disable:
      - 'paths/server'

```
