### DISCUSSION TITLE
Support for golang interface type

### DISCUSSION THREAD

**Discussion by haroongelato** [ogen-go/ogen#533] [Q&A]
Hi,
I have a spec smth like this:
```yaml
groupedRow:
      type: object
      properties:
        group:
          type: integer
        description:
          type: interface //I want to make this field interface type
        showSubtotal:
          type: boolean
```
I require `interface` type in my generated code.
I am new to Open API spec code generation, any help would be appreciated :)
