### DISCUSSION TITLE
Handle null field

### DISCUSSION THREAD

**Discussion by Williamzxc1996** [ogen-go/ogen#537] [General]
In the api.yaml I have a field in request payload defined as
```
          properties:
            metadata:
              type: object
```

And in the actual request, we sometime will send out null metadata like below
```
  "message": {
     ...
    "metadata": null,
     ...
  }
```
However, seems like ogen can't handle it. It will return 400. Can anyone help me with this problem, thanks!

**Comment by ghost** [comment]
You should add `nullable` attribute to the `metadata` property schema.
```yaml
          properties:
            metadata:
              type: object
              nullable: true
```
