### ISSUE TITLE
feat: support config for generation

### ISSUE THREAD

**Issue by ernado** [ogen-go/ogen#1078]
Like https://gqlgen.com/

```yaml
models:
  ID: # The GraphQL type ID is backed by
    model:
      - github.com/99designs/gqlgen/graphql.IntID # a go integer
      - github.com/99designs/gqlgen/graphql.ID # or a go string
```

- [ ] Add `--config` option
- [ ] Default to `ogen.yml`
- [ ] Add all command line options to config
