### ISSUE TITLE
Use generated client in security source implementations

### ISSUE THREAD

**Issue by vallahaye** [ogen-go/ogen#1134]
First of all, many thanks for open-sourcing this awesome piece of software. It's been a real pleasure working with Ogen so far.

### Description

Many APIs are not OAuth-compatible, and obtaining an access token to call restricted endpoints is done by calling a non-standard authentication endpoint (`/v1/users/login` for example).

This endpoint is often described in the OpenAPI specification of said APIs, and is therefore available in the client generated by Ogen. It would be very useful to be able to access the generated client from a security source implementation so that we can easily call the authentication endpoint.

To do so, I propose to add a new Ogen extension to security schemes that would alter the signature of the `SecuritySource` interface and the calling site.

For example:

```yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-ogen-use-client: true
    CustomBearerAuth:
      type: http
      scheme: bearer
      x-ogen-custom-security: true
      x-ogen-use-client: true
```

This specification would generate the following interface:

```go
type SecuritySource interface {
  BearerAuth(ctx context.Context, operationName string, client *Client) (BearerAuth, error)
  CustomBearerAuth(ctx context.Context, operationName string, req *http.Request, client *Client) error
}
```

I'm willing to help you implement this proposal if it gets accepted!
