### ISSUE TITLE
Integer type not supported as a schema type.

### ISSUE THREAD

**Issue by i4ki** [ogen-go/ogen#1144]
### What version of ogen are you using?

```bash
v0.79.0
```

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

Add the schema below:
```
components:
  schemas:
    safeInteger:
      description: "MAX_SAFE_INTEGER"
      type: integer
      format: int64
      maximum: 9007199254740991
      minimum: 0
```

### What did you expect to see?

Correctly parsed and then being able to reference it with `'#/components/schemas/safeInteger'`. 

### What did you see instead?

```
  - openapi.yml:1166:7 -> unknown parameter location ""
	  1164 |
	  1165 |     safeInteger:
	→ 1166 |       type: integer
	  1167 |       description: "MAX_SAFE_INTEGER"
	  1168 |       format: int64
	  1169 |       maximum: 9007199254740991
	  1170 |       minimum: 0
```
