### ISSUE TITLE
feat(gen): Generate single type for a parameter definition

### ISSUE THREAD

**Issue by urandom** [ogen-go/ogen#1177]
### Description
Given the following definition:
```
components:
  securitySchemes:
  parameters:
    PathParam:
      in: path
      name: path-param
      required: true
      schema:
        type: string
        enum: ["val1", "val2"]
```

The generator creates a separate type for this definition whenever this parameter is used. If two operations (oper1, oper2) use this parameter, there will be two generated types (Oper1PathParam, Oper2PathParam). This makes it very difficult to handle such parameters in a common middleware, since they cannot be converted to a string, as that is just an underlying type.
