### ISSUE TITLE
CLI option to validate-only the schema

### ISSUE THREAD

**Issue by adrianlungu** [ogen-go/ogen#1198]
### Description

Tried `redocly` and `vacuum` for validating an OpenAPI schema, but there are still differences with regards to what `ogen` checks vs what the other tools test so it would be nice to have a `validate-only` cli option to be able to use it in CI to check if the schema is valid from ogen's perspective. 

For example: 

```
        - name: status
          description: The status
          example: active
          schema:
            type: string
            items:
              type: string
              enum:
                - active
                - inactive
```

This throws a `items: unexpected field for type "string"` via `ogen` but `redocly` and `vacuum` consider this a valid OpenAPI spec for some reason.
