### ISSUE TITLE
Encode/Decode: Unmarshal creates error, while marshal works fine

### ISSUE THREAD

**Issue by cugu** [ogen-go/ogen#1254]
### What version of ogen are you using?

v1.2.0

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

I have a server created by ogen, which serves user objects with an optional team field, that is a string array.
`json.Marshal` this with teams set to `nil` becomes `null` which I think is reasonable.
However `json.Unmarshal` fails and always expects an array.

```yaml
components:
  schemas:
    User:
      type: object
      properties:
        teams: { type: array, description: "The user teams", items: { type: string } }
      required: []
```

```go
func TestUserMarshal(t *testing.T) {
	user := api.User{
		Teams: nil,
	}

	b, err := json.Marshal(user)
	if err != nil {
		t.Errorf("error marshalling user: %v", err)
	}

	var u2 api.User
	if err := json.Unmarshal(b, &u2); err != nil {
		t.Errorf("error unmarshalling user: %v", err)
	}
}
```

### What did you expect to see?

Unmarshal without error

### What did you see instead?

Unmarshal created an error:

```log
decode User: callback: decode field "teams": "[" expected: unexpected byte 110 'n' at 33
```
