### ISSUE TITLE
Servers: Variables do not support non-enums

### ISSUE THREAD

**Issue by atombender** [ogen-go/ogen#1272]
Given a server list like this:

```yaml
servers:
- url: https://{hostPort}/v{version}
  x-ogen-server-name: development
  variables:
    version:
      description: API version
      default: UNKNOWN  # Ogen requires a dummy default here
    hostPort:
      description: Host and port
      default: UNKNOWN  # Ogen requires a dummy default here
```

This will generate the following validation code:

```go
func (s DevelopmentServer) Build() (string, error) {
	zeroOr := func(s string, def string) string {
		if s == "" {
			return def
		}
		return s
	}
	s.HostPort = zeroOr(s.HostPort, "UNKNOWN")
	// Validate "hostPort"
	switch s.HostPort {
	default:
		return "", errors.Errorf("param %q: unexpected value %q", "hostPort", s.HostPort)
	}
	...
```

This means it's not possible to create structs with arbitrary data:

```go
srv := DevelopmentServer{
	HostPort: "localhost:8080",
	Version: "2024-06-29",
}
```

as this will fail with:

```
param "hostPort": unexpected value "localhsot:8080":
```

This is in violation of the [OpenAPI spec](https://spec.openapis.org/oas/v3.1.0#server-variable-object), which says the `enum` is optional (emphasis mine):

> An enumeration of string values to be used ***if*** the substitution options are from a limited set

The validation template should just skip non-set values, e.g.:

```tmpl
	{{- if $p.Spec.Enum }}
	// Validate {{ quote $p.Spec.Name }}
	switch s.{{ $p.Name }} {
	{{- range $e := $p.Spec.Enum }}
	case {{ quote $e }}:
	{{- end }}
	default:
		return "", errors.Errorf("param %q: unexpected value %q", {{ quote $p.Spec.Name }}, s.{{ $p.Name }})
	}
	{{- end }}
```
