### ISSUE TITLE
Support custom `format` types.

### ISSUE THREAD

**Issue by abemedia** [ogen-go/ogen#1335]
### Description

I'd like to propose adding support for custom `format` types. These could come from the configuration. Maybe something like the following example:

```yaml
generator:
  formats:
    decimal: github.com/shopspring/decimal.Decimal
```

This would result in a field with `format: decimal` to be of the type `decimal.Decimal` from the package `github.com/shopspring/decimal`.

Alternatively, we could implement this as an extension e.g. 

```yaml
type: string
x-ogen-type: github.com/shopspring/decimal.Decimal
```

We can implement some checks to ensure the package is importable, as well as checking that the type implements one of the following interfaces:

```go
interface {
  Encode(e *jx.Encoder)
  Decode(d *jx.Decoder) error
}
```

```go
interface {
  json.Marshaler
  json.Unmarshaler
}
```

```go
interface {
  encoding.TextMarshaler
  encoding.TextUnmarshaler
}
```

Based on which of the interfaces it implements we can use a different template for encoding and decoding the value.

I'm happy to implement this feature, just wanted to first check if such a feature would be accepted and get alignment on the way it's configured.

**Comment by tdakkota** [comment]
> I'm happy to implement this feature, just wanted to first check if such a feature would be accepted and get alignment on the way it's configured.

It would be nice. This feature was requested before.

I think it is better to configure it via extension `x-go-type`, since it also used by [oapi-codegen](https://github.com/oapi-codegen/oapi-codegen/blob/9c09ef9e9d4be639bd3feff31ff2c06961421272/pkg/codegen/extension.go#L9)
and [go-swagger](https://github.com/go-swagger/go-swagger/blob/bb4bd9ac1bae0e8bdb30903ba54618caeb1e3643/generator/types.go#L50).

**Comment by abemedia** [comment]
Thanks for getting back to me on this @tdakkota!

Both oapi-codegen and go-swagger use different formats though:

oapi-codegen
```yaml
x-go-type: googleuuid.UUID
x-go-type-import:
  path: github.com/google/uuid
  name: googleuuid
```

go-swagger
```yaml
x-go-type:
  import:
    package: github.com/google/uuid
    alias: googleuuid
  type: UUID
```

I personally still prefer the idea of writing a single field e.g.

```yaml
x-go-type: github.com/google/uuid.UUID
```

We could also automatically alias it if there's a clash between package names.

What's your preference?
