### ISSUE TITLE
bug(headers): nested object schema throws

### ISSUE THREAD

**Issue by ayuhito** [ogen-go/ogen#1381]
### What version of ogen are you using?

```bash
$ go list -m github.com/ogen-go/ogen
github.com/ogen-go/ogen v1.8.1
```

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

`aws-lambda-web-adapter` injects a serialised JSON request context in the [`x-amzn-request-context`](https://github.com/awslabs/aws-lambda-web-adapter?tab=readme-ov-file#request-context) header which I wanted to include in the API spec. However, it seems that a nested schema in headers will throw. It's understandable since this is a little non-standard, but I don't think I see anything that seems to deny this behaviour in the OpenAPI 3 spec either?

```yaml
components:
  headers:
    X-Amzn-Request-Context:
      in: header
      schema:
        type: object
        properties:
          authorizer:
            type: object
            properties:
              claims:
                type: string
```

Note if I remove `claims` and set `authorizer` to `type: string`, this will actually succeed in code-gen (although I haven't tested actual functionality).

In an ideal world, I would like to be able to do something like this with a few required properties:

```yaml
components:
  headers:
    X-Amzn-Request-Context:
      in: header
      schema:
        type: object
        properties:
          authorizer:
            type: object
            properties:
              claims:
                type: object
                properties:
                  email:
                    type: string
                    format: email
```

### What did you expect to see?

Successful generation.

### What did you see instead?

```
generate:
    main.run
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/cmd/ogen/main.go:379
  - build IR:
    main.generate
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/cmd/ogen/main.go:72
  - make ir:
    github.com/ogen-go/ogen/gen.NewGenerator
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/gen/generator.go:110
  - operations:
    github.com/ogen-go/ogen/gen.(*Generator).makeIR
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/gen/generator.go:128
  - path "/entry-codes": post:
    github.com/ogen-go/ogen/gen.(*Generator).makeOps
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/gen/generator.go:169
  - parameters:
    github.com/ogen-go/ogen/gen.(*Generator).generateOperation
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/gen/gen_operation.go:47
  - "X-Amzn-Request-Context":
    github.com/ogen-go/ogen/gen.(*Generator).generateParameter
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/gen/gen_parameters.go:174
  - field "Authorizer":
    github.com/ogen-go/ogen/gen.isParamAllowed
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/gen/gen_parameters.go:215
  - nested objects not allowed:
    github.com/ogen-go/ogen/gen.isParamAllowed
        /Users/user/go/pkg/mod/github.com/ogen-go/ogen@v1.8.1/gen/gen_parameters.go:211
exit status 1
```

On a side note, thank you for this library! Makes a world of a difference when maintaining APIs.

**Comment by tdakkota** [comment]
> `aws-lambda-web-adapter` injects a serialised JSON request context 

[You should `content` instead of `schema`](https://swagger.io/docs/specification/v3_0/describing-parameters/#schema-vs-content):
```yaml
components:
  headers:
    X-Amzn-Request-Context:
      content: 
        application/json:
          schema: 
            type: object
            properties:
              authorizer:
                type: object
                properties:
                  claims:
                    type: object
                    properties:
                      email:
                        type: string
                        format: email

```

Encoding of nested objects is not defined by OpenAPI spec, so it is not implemented.
