### ISSUE TITLE
Can't use variables inside clientCredentials.tokenUrl

### ISSUE THREAD

**Issue by ngalaiko** [ogen-go/ogen#1449]
### What version of ogen are you using?

v1.12.0

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

I've parameterized clientCredentials.tokenUrl with variables:

```yaml

servers:
  - description: Development
    url: https://iam.{domain}/v2
    variables:
      domain:
        default: "<redacted>"

components:
  securitySchemes:
    OAuth2:
      description: "OAuth 2.0 authentication"
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://auth.{domain}/v2/token"
          scopes: {}
```

### What did you expect to see?

No error.

### What did you see instead?

```
  - openapi.yaml:366:21 -> "tokenUrl" MUST be in the form of a URL: parse "https://auth.{domain}/v2/token": invalid character "{" in host name
          363 |       type: oauth2
          364 |       flows:
          365 |         clientCredentials:
        → 366 |           tokenUrl: "https://auth.{domain}/v2/token"
          367 |           scopes: {}
          368 |
```
