### ISSUE TITLE
BUG: Omitted optional arrays are validated for length anyway

### ISSUE THREAD

**Issue by oniony** [ogen-go/ogen#1461]
### What version of ogen are you using?

v1.10.1

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

When a schema has an optional array with a minimum length, an object with the field omitted cannot be decoded as the generated code always checks the array length: it does not handle a `nil` slice when the field is optional.

```
type: object
required:
  - apples
properties:
  apple:
    type: string
    description: Apple name
  banana:
    type: array
    minItems: 1
    items:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
        value:
          type: string
```

Attempting to decode `{"apple": "russet"}` with no `banana` field should work as the `banana` field is optional.

### What did you see instead?

Instead there is a validation failure that the `banana` field is empty:

>decode response: default (code 500): validate: invalid: errors (invalid: [0] (invalid: banana (array: len 0 less than minimum 1)))

The generated code validates the array length always, even if the array is optional and has a value of `nil`:

```
func (s *Blah) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.Array{
			MinLength:    1,
			MinLengthSet: true,
			MaxLength:    0,
			MaxLengthSet: false,
		}).ValidateLength(len(s.Banana)); err != nil {
			return errors.Wrap(err, "array")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "banana",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
```

I would expect the generated code to check whether the array is optional is optional and skip the length check if s.Banana is `nil`.
