### ISSUE TITLE
gen: find a better way to deal with names that do not fit the go specification

### ISSUE THREAD

**Issue by shadowspore** [ogen-go/ogen#459]
Sample schema component:
```yaml
components:
  schemas:
    12345:
      type: object
      properties:
        test:
          type: string
```

Generated type:
```go
// Ref: #/components/schemas/12345
type R12345 struct {
	Test OptString "json:\"test\""
}
```

It would be nice to generate more meaningful name prefixes based on context.
