### ISSUE TITLE
[server]: using multi securitySchemes on same path cause incorrect code

### ISSUE THREAD

**Issue by giautm** [ogen-go/ogen#662]
### What version of ogen are you using?

```bash
$ go list -m github.com/ogen-go/ogen
```
Output: `github.com/ogen-go/ogen v0.54.1`

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

```
paths:
  /some-path:
    post:
      operationId: somePath
      security:
        - partnerID: []
          accessKey: []
components:
  securitySchemes:
    partnerID:
      type: apiKey
      name: X-Partner-ID
      in: header
    accessKey:
      type: apiKey
      name: X-Access-Key
      in: header
```

### What did you expect to see?

Code generate correctly

### What did you see instead?

<img width="815" alt="Screen Shot 2022-11-09 at 03 18 37" src="https://user-images.githubusercontent.com/12751435/200666814-5e6060fe-3e4c-4ef1-9387-2d5062b68797.png">
