### ISSUE TITLE
gen: Duplicate generated fields with similar names 

### ISSUE THREAD

**Issue by seblex** [ogen-go/ogen#896]
### What version of ogen are you using?

v0.66.0

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

I create params:
```
XReqIDHeaderParam:
  in: "Header"
  name: "X-Req-ID"
  required: false
  schema:
    type: "string"
  description: "Request unique ID"

XreqidQueryParam:
  in: "query"
  name: "x-req-id"
  required: false
  schema:
    type: "string"
  description: "Request unique ID"
```
### What did you see?

```
// DownloadParams is parameters of Download operation.
type DownloadParams struct {
	// Request unique ID.
	XReqID OptString
	// Request unique ID.
	XReqID OptString
}
```

### I suggest

Created params:
```
XReqIDHeaderParam:
  in: "Header"
  name: "X-Req-ID"
  x-ogen-name: "XReqIDHeader"
  required: false
  schema:
    type: "string"
  description: "Request unique ID"

XreqidQueryParam:
  in: "query"
  name: "x-req-id"
  x-ogen-name: "XReqIDQuery"
  required: false
  schema:
    type: "string"
  description: "Request unique ID"
```
Generated params:
```
// DownloadParams is parameters of Download operation.
type DownloadParams struct {
	// Request unique ID.
	XReqIDHeader OptString
	// Request unique ID.
	XReqIDQuery OptString
}
```
I do not insist on this decision.
