### ISSUE TITLE
use mapping key for generated discriminator constants

### ISSUE THREAD

**Issue by Liooo** [ogen-go/ogen#967]
Currently, this schema 

```yaml
components:
  schemas:
    Pet:
      oneOf:
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Cat'
      discriminator:
        propertyName: type
        mapping:
          dog: '#/components/schemas/Dog'
          cat: '#/components/schemas/Cat'
```

compiles into this:

```go
type Pet struct {
  Type PetType
}

type PetType string

const (
  PetTypeDog PetType = "PetTypeDog"
  PetTypeCat PetType = "PetTypeCat"
)
```

It'd be nicer if the discriminator strings are like the following.

```go
const (
  PetTypeDog PetType = "dog"
  PetTypeCat PetType = "cat"
)
```

The reason behind being:

- it's shorter and simpler, without causing naming conflict given the mapping keys are unique
- allows the definition of the same values for different keys
  e.g.
  ```yaml
  mapping:
    - cat: "#/components/schemas/mammal"
    - dog: "#/components/schemas/mammal"
    - lizard: "#/components/schema/reptile"
  ```
- (though not that important) most of the frontend typescript/javascript generators I know of have this behavior
