### ISSUE TITLE
Validation of responses?

### ISSUE THREAD

**Issue by tadejsv** [ogen-go/ogen#996]
Is there any plan to add validation of responses?

For example, if I have a schema `User`

```
    User:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: user@email.com
        website:
          type: string
```

which I use in a request, it gets validated (if I would set `email` to `"hey"`, I would get an error).

But if this schema is part of the response it does not get validated - e.g., I can send `"hey"` as `email`, and it goes throught without problems.
